
set (wxWidget_sources
    # wx_core
    ${CMAKE_CURRENT_LIST_DIR}/common/accelcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/accesscmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/addremovectrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/affinematrix2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/anidecod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/animatecmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/appcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/artprov.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/artstd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/arttango.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/bmpbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/bmpbtncmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/bmpcboxcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/bookctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/btncmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/cairo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/calctrlcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/checkboxcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/checklstcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/choiccmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/clipcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/clrpickercmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/cmdproc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/cmndata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/colourcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/colourdata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/combocmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/containr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/cshelp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/ctrlcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/ctrlsub.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/datavcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dcbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dcbufcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dcgraph.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dcsvg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dirctrlcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dlgcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dndcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dobjcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/docmdi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/docview.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dpycmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dseldlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/effects.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/event.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fddlgcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filectrlcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filehistorycmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filepickercmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fldlgcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fontcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fontdata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fontenumcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fontmap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fontpickercmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fontutilcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/framecmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fs_mem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/gaugecmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/gbsizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/gdicmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/geometry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/gifdecod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/graphcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/gridcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/headercolcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/headerctrlcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/helpbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/hyperlnkcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/iconbndl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagall.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagbmp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagfill.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imaggif.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagiff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagjpeg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagpcx.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagpng.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagpnm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagtga.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagtiff.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/imagxpm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/lboxcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/listctrlcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/markupparser.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/matrix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/menucmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/modalhook.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/mousemanager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/msgout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/nbkbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/notifmsgcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/odcombocmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/overlaycmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/ownerdrwcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/panelcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/paper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/persist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/pickerbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/popupcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/preferencescmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/prntbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/quantize.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/radiobtncmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/radiocmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/rearrangectrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/rendcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/rgncmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/richtooltipcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/scrolbarcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/settcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/sizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/slidercmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/spinbtncmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/spinctrlcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/srchcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/statbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/statbmpcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/statboxcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/statlinecmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stattextcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stockitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/taskbarcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/tbarbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/textcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/textentrycmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/textmeasurecmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/toplvcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/treebase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/uiactioncmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/utilscmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/valgen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/validate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/valnum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/valtext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/wincmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/windowid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/wrapsizer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/xpmdecod.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/aboutdlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/activityindicator.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/animateg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/bannerwindow.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/bmpcboxg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/busyinfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/buttonbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/calctrlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/choicbkg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/choicdgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/clrpickerg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/collheaderctrlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/collpaneg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/combog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/commandlinkbuttong.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/creddlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/datavgen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/datectlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/dcpsg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/dirctrlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/dragimgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/editlbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/filectrlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/filepickerg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/fontpickerg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/graphicc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/grid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/gridctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/grideditors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/gridsel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/headerctrlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/helpext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/hyperlinkg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/infobar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/laywin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/listbkg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/logg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/markuptext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/msgdlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/notifmsgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/numdlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/odcombo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/preferencesg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/printps.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/prntdlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/progdlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/propdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/renderg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/richmsgdlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/richtooltipg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/rowheightcache.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/sashwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/scrlwing.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/selstore.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/spinctlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/splash.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/splitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/srchctlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/statbmpg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/stattextg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/statusbr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/textdlgg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/timectrlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/tipdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/tipwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/toolbkg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/treebkg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/treectlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/treelist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/vlbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/vscroll.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/wizard.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/aboutdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/accel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/anybutton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/app.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/appprogress.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/artmsw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/bitmap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/bmpbuttn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/bmpcbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/brush.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/button.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/calctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/caret.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/checkbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/checklst.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/choice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/clipbrd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/colordlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/colour.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/combo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/combobox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/commandlinkbutton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/control.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/cursor.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/customdraw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/datecontrols.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/datectrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/datetimectrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dcclient.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dcmemory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dcprint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dcscreen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dialog.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dialup.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dib.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dirdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/display.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dragimag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/enhmeta.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/evtloop.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/fdrepdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/filedlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/font.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/fontdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/fontenum.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/fontutil.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/frame.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/gauge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/gdiimage.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/gdiobj.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/gdiplus.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/graphics.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/graphicsd2d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/headerctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/helpchm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/helpwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/hyperlink.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/icon.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/imaglist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/iniconf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/joystick.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/listbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/listctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/main.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/mdi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/menu.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/menuitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/metafile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/minifram.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/msgdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/nativdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/nativewin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/nonownedwnd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/notebook.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/notifmsg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/access.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/activex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/automtn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/comimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/dataobj.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/dropsrc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/droptgt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/oleutils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/safearray.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ole/uuid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/ownerdrw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/palette.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/pen.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/popupwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/printdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/printwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/progdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/radiobox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/radiobut.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/region.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/renderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/richmsgdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/richtooltip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/rt/notifmsgrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/rt/utilsrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/scrolbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/settings.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/slider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/sound.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/spinbutt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/spinctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/statbmp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/statbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/statline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/stattext.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/statusbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/systhemectrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/taskbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/taskbarbutton.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/textctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/textentry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/textmeasure.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/tglbtn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/timectrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/toolbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/tooltip.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/toplevel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/treectrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/uiaction.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/utilsgui.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/utilswin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/uxtheme.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/volume.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/window.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrc/xmlreshandler.cpp

    # wx_aui
    ${CMAKE_CURRENT_LIST_DIR}/aui/auibar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/auibook.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/barartmsw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/dockart.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/floatpane.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/framemanager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/tabart.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/tabartmsw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/aui/tabmdi.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrc/xh_aui.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrc/xh_auitoolb.cpp

    # wx_html
    ${CMAKE_CURRENT_LIST_DIR}/generic/htmllbox.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/chm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/helpctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/helpdata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/helpdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/helpfrm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/helpwnd.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/htmlcell.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/htmlfilt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/htmlpars.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/htmltag.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/htmlwin.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/htmprint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_dflist.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_fonts.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_hline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_image.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_links.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_list.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_pre.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_span.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_style.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/m_tables.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/styleparams.cpp
    ${CMAKE_CURRENT_LIST_DIR}/html/winpars.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/helpbest.cpp

    # wx_propgrid
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/advprops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/editors.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/manager.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/property.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/propgrid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/propgridiface.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/propgridpagestate.cpp
    ${CMAKE_CURRENT_LIST_DIR}/propgrid/props.cpp

    # wx_ribbon
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/art_aui.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/art_internal.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/art_msw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/bar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/buttonbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/control.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/gallery.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/page.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/panel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/ribbon/toolbar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrc/xh_ribbon.cpp

    # wx_stc (Scintilla)
    ${CMAKE_CURRENT_LIST_DIR}/stc/PlatWX.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stc/ScintillaWX.cpp
    ${CMAKE_CURRENT_LIST_DIR}/stc/stc.cpp

    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/AutoComplete.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/CallTip.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/CaseConvert.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/CaseFolder.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/Catalogue.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/CellBuffer.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/CellBuffer.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/CharClassify.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/ContractionState.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/Decoration.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/Document.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/EditModel.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/EditView.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/Editor.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/ExternalLexer.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/Indicator.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/KeyMap.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/LineMarker.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/MarginView.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/PerLine.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/PositionCache.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/RESearch.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/RunStyles.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/ScintillaBase.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/Selection.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/Style.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/UniConversion.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/ViewStyle.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/src/XPM.cxx

    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/Accessor.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/CharacterCategory.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/CharacterSet.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/LexerBase.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/LexerModule.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/LexerNoExceptions.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/LexerSimple.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/PropSetSimple.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/StyleContext.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexlib/WordList.cxx

    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexA68k.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAbaqus.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAda.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAPDL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAsm.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAsn1.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexASY.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAU3.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAVE.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexAVS.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexBaan.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexBash.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexBasic.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexBatch.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexBibTeX.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexBullant.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCaml.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCLW.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCmake.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCOBOL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCoffeeScript.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexConf.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCPP.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCrontab.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCsound.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexCSS.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexD.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexDiff.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexDMAP.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexDMIS.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexECL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexEDIFACT.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexEiffel.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexErlang.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexErrorList.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexEScript.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexFlagship.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexForth.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexFortran.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexGAP.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexGui4Cli.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexHaskell.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexHex.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexHTML.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexInno.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexJSON.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexKix.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexKVIrc.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexLaTeX.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexLisp.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexLout.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexLua.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMagik.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMake.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMarkdown.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMatlab.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMetapost.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMMIXAL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexModula.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMPT.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMSSQL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexMySQL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexNimrod.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexNsis.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexNull.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexOpal.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexOScript.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPascal.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPB.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPerl.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPLM.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPO.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPOV.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPowerPro.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPowerShell.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexProgress.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexProps.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPS.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexPython.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexR.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexRebol.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexRegistry.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexRuby.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexRust.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexScriptol.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexSmalltalk.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexSML.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexSorcus.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexSpecman.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexSpice.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexSQL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexSTTXT.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexTACL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexTADS3.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexTAL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexTCL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexTCMD.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexTeX.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexTxt2tags.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexVB.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexVerilog.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexVHDL.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexVisualProlog.cxx
    ${CMAKE_CURRENT_LIST_DIR}/stc/scintilla/lexers/LexYAML.cxx

    # wx_richtext
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextbuffer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextctrl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextformatdlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtexthtml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextimagedlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextprint.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextstyledlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextstyles.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextsymboldlg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/richtext/richtextxml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xrc/xh_richtext.cpp

    # wx_xml (required by wx_richtext)
    ${CMAKE_CURRENT_LIST_DIR}/common/xtixml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/xml/xml.cpp

    # wx_webview
    ${CMAKE_CURRENT_LIST_DIR}/common/webview.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/webviewarchivehandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/webviewfshandler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/webview_edge.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/webview_ie.cpp


    # wxBase (these files are normally compiled into base library)
    ${CMAKE_CURRENT_LIST_DIR}/common/any.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/appbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/arcall.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/arcfind.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/archive.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/arrstr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/base64.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/clntdata.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/cmdline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/config.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/convauto.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/datetime.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/datetimefmt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/datstrm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dircmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dynlib.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/dynload.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/encconv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/evtloopcmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/ffile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/file.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fileback.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fileconf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filefn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filename.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filesys.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filtall.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/filtfind.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fmapbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fs_arc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fs_filter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fs_mem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/fswatchercmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/hash.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/hashmap.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/init.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/intl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/ipcbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/languageinfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/list.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/log.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/longlong.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/lzmastream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/memory.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/mimecmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/module.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/msgout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/mstream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/numformatter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/object.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/platinfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/powercmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/process.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/regex.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/secretstore.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/sstream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stdpbase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stdstream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stopwatch.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/strconv.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/string.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stringimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/stringops.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/strvararg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/sysopt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/tarstrm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/textbuf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/textfile.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/threadinfo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/time.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/timercmn.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/timerimpl.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/tokenzr.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/translation.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/txtstrm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/unichar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/uri.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/ustring.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/variant.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/wfstream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/wxcrt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/wxprintf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/xlocale.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/xti.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/xtistrm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/zipstrm.cpp
    ${CMAKE_CURRENT_LIST_DIR}/common/zstream.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generic/fswatcherg.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/basemsw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/crashrpt.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dde.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/debughlp.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dir.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/dlmsw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/evtloopconsole.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/fswatcher.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/mimetype.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/power.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/regconf.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/registry.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/secretstore.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/snglinst.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/stackwalk.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/stdpaths.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/thread.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/timer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/utils.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/utilsexc.cpp
    ${CMAKE_CURRENT_LIST_DIR}/msw/volume.cpp

)


set (wxCLib_sources
    # wx_wxjpeg
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jaricom.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcapimin.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcapistd.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcarith.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jccoefct.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jccolor.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcdctmgr.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jchuff.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcinit.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcmainct.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcmarker.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcmaster.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcomapi.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcparam.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcprepct.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jcsample.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jctrans.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdapimin.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdapistd.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdarith.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdatadst.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdatasrc.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdcoefct.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdcolor.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jddctmgr.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdhuff.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdinput.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdmainct.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdmarker.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdmaster.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdmerge.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdpostct.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdsample.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jdtrans.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jerror.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jfdctflt.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jfdctfst.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jfdctint.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jidctflt.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jidctfst.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jidctint.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jmemmgr.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jmemnobs.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jquant1.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jquant2.c
    ${CMAKE_CURRENT_LIST_DIR}/jpeg/jutils.c

    # wx_wxtiff
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_aux.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_close.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_codec.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_color.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_compress.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_dir.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_dirinfo.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_dirread.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_dirwrite.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_dumpmode.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_error.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_extension.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_fax3.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_fax3sm.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_flush.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_getimage.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_jbig.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_jpeg.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_jpeg_12.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_luv.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_lzma.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_lzw.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_next.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_ojpeg.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_open.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_packbits.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_pixarlog.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_predict.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_print.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_read.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_strip.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_swab.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_thunder.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_tile.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_version.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_warning.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_webp.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_win32.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_write.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_zip.c
    ${CMAKE_CURRENT_LIST_DIR}/tiff/libtiff/tif_zstd.c

    # wx_wxpng
    ${CMAKE_CURRENT_LIST_DIR}/png/png.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngerror.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngget.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngmem.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngpread.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngread.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngrio.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngrtran.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngrutil.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngset.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngtrans.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngwio.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngwrite.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngwtran.c
    ${CMAKE_CURRENT_LIST_DIR}/png/pngwutil.c
    ${CMAKE_CURRENT_LIST_DIR}/png/arm/arm_init.c
    ${CMAKE_CURRENT_LIST_DIR}/png/arm/filter_neon_intrinsics.c
    ${CMAKE_CURRENT_LIST_DIR}/png/arm/palette_neon_intrinsics.c
    ${CMAKE_CURRENT_LIST_DIR}/png/intel/intel_init.c
    ${CMAKE_CURRENT_LIST_DIR}/png/intel/filter_sse2_intrinsics.c

    # wx_wxzlib
    ${CMAKE_CURRENT_LIST_DIR}/zlib/adler32.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/compress.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/crc32.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/deflate.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/gzclose.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/gzlib.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/gzread.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/gzwrite.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/infback.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/inffast.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/inflate.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/inftrees.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/trees.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/uncompr.c
    ${CMAKE_CURRENT_LIST_DIR}/zlib/zutil.c

    # wx_wxregex
    ${CMAKE_CURRENT_LIST_DIR}/regex/regcomp.c
    ${CMAKE_CURRENT_LIST_DIR}/regex/regerror.c
    ${CMAKE_CURRENT_LIST_DIR}/regex/regexec.c
    ${CMAKE_CURRENT_LIST_DIR}/regex/regfree.c

    # wx_wxexpat
    ${CMAKE_CURRENT_LIST_DIR}/expat/expat/lib/xmlparse.c
    ${CMAKE_CURRENT_LIST_DIR}/expat/expat/lib/xmlrole.c
    ${CMAKE_CURRENT_LIST_DIR}/expat/expat/lib/xmltok.c

    # wxBase
    ${CMAKE_CURRENT_LIST_DIR}/common/extended.c
)
